module.exports={
    name:'string',
    image:{
        resize_url:'string',
        resize_thumbnail:'string'
    },
    averagePrice:'string',
    isVeg:'string',
    status:'string',
    isCustomizable:'string',
    fromTime:'string',
    toTime:'string',
    isRecommanded:'string',
    maxQuantity:'string'
}